
var arrlang={
  'en':{
    'login':'Login',
    'vision':'Vision',
    'mission':'Mission',
    'value':'Value',
    'help':'Help',
    'developer':'Developer',
    'welcome':'Welcome To Debre Tabor University Smart ID Card System to start please press login',
    'fdescription':' Debre Tabor University tries hard to become one of the top universities in the country in quality education in 2020 G.C',
    'smart':'Smart ID Card System for ',
    'dt':'Debre Tabor University (SMICS)',
    'name':'Developer Name',
    'email':'Email',
    'phone':'Phone No',
    'close':'Close',
    'about':'About Developer',
    'list':'Basic Listts',
    'val':'Values',
    'first':'Customer First',
    'teamwork':'Team Work',
    'quality':'Quality',
    'inovation':'Inovation',
    'scalup':'Success and Scale up',
    'ethics':'Devoted to Ethics',
    'please': 'Please Enter User Name and Password',
    'ema':'Email (UserName)',
    'password':'Password',
    'level':'Level',
    'superadmin':'Super Admin',
    'stsa':'Student Service Admin',
    'stss':'Student Service Staff',
    'ssa':'Staff Service Ademin',
    'sss':'Staff Service Staff',
    'ca':'Cafeteria Admin',
    'cs':'Cafeteria Staff',
    'sa':'Security Admin',
    'ss':'Security Staff',
    'la':'Library Admin',
    'ls':'Library Staff',
    'dta':'Dormitary Admin',
    'dts':'Dormitary Staff',
    'remember':'Remember Me',

    'samfdtusmics':'Super Admin Module for Debere Tabor University Smart ID Card System',
    'date':'Date:-',
    'logedas':'Loged As:-',
    'home':'Home',
    'cua':'Create User Acount',
    'user managment':'User Management',
    'staff managment':'Staff Management',
    'student s managment':'Student Service Management',
    'cafeteria managment':'Cafeteria Management',
    'library managment':'Library Management',
    'dorm a managment':'Dorm Attendance Management',
    'security managment':'Security Management',
    'academics':'academics',
    'academics managment':'Acadeemics Management',
    'change password':'Chane Password',
    'logout':'Logout',
    'dtusicbsps':'Debre Tabor University Single ID Card Based Service Provider System',
    'user register':'User Register  Successfully',
    'user not register':'User Not Registered Successfullu',
    'view use':'View User Acount',
    'user deleted':'User Acount Deleted Successfully',
    'user not deleted':'User Acount not Deleted ',
    'data not avialable':'Data is not avialable please try again',
    'view activated user':'View Activated User',
    'view deactivated user':'View Deactivated User',
    'register staff acount':'Register Staff Acount',
    'id':'ID',
    'staff name':'Staff Name',
    'select user type':'Select User Level',
    'save acount':'Save ',
    'cancle':'Cancle',
    'register faculty':'Register Faculty Here',
    'faculty':'Faculty:-',
    'status':'Status:-',
    'search faculty':'Search Faculty ',
    'select faculty':'Select Faculty',
    'search department':'Search Department ',
    'department':'Department',
    'select department':'Select Department',
    'faculty entered':'Faculty are Entered Successfully',
    'return':'Return',
    'return to home page':'Return to Home page',
    'please sfte department':'Please Seclect Faculty to enter Department',
    'reset':'Reset',
    'department entered':'Department enterd Successfully',
    'department not entered':'Department not entered',
    'please sdte stream':'Please Select Department to enter Specialization',
    'stream':'Specialization',
    'stream entered':'Specialization entered Successfully',
    'stream not entered':'Specialization are not entered',
    'press this tab tdfd':'Press this tab to display Faculty Data',
    'please eyunap':'Please enter your UserName and Password',
    'old password':'Old Password:- ',
    'new password':'New Password:-',
    'confirm password':'Confirm Password:-',
    'change':'Change',
    'view user':'View System Users',
    'user id':'User ID',
    'full name':'Full Name',
    'user status':'User Status',
    'action':'Action',
    'user name':'User Name',
    'user type':'User Type ',

    'samfdtusmicsfstaff':'Super Admin Module for Debre Tabor University Smart ID Card System for Staff',
    'staff registration':'Staff Registration',
    'staff barcode generation':'Staff Barcode Generation',
    'register staff':'Register Staff Here',
    'sex':'Sex',
    'year':'Year', 
    'ac_year':'Ac_Year',
    'upload photo':'Upload Photo',
    'remove':'Remove',
    'select image':'Select Photo',
    'female':'Female',
    'male':'Male',
    'generate barcode':'Generate Barcode',
    'select stream':'Select Specialization',
    'change image':'Change',
    'list of employee data':'List of Staff Data in the System',
    'staff data deleted':'Staff Data are Deleted Successfully',
    'staff data not deleted':'Staff Data are not Deleted',
    'staff avialable':'Staff are Avialabe in the Database',
    'ac_year':'Ac_year',
    'status':'Status',

    'samfdtusmicsfstudent':'Super Admin Module for Debre Tabor University Smart ID Card System for Student',
    'student registration':'Student Registration',
    'student barcode registration':'Student Barcode Registration',
    'year':'Year',
    'student avialable':'Students are Avialabe in the Database',

    'samfdtucms':'Super Admin Module for DebreTabor University Smart ID Card System for Cafeteria',
    'register non cafe':'Register Non Cafe Students',
    'manage data':'Manage Data',
    'generate cafe user report':'Generate Cafe User Repeort',
    'generate non cafe report':'Generate Non Cafe Report',
    'generate rerort for non cafe student in the date range':'Generate Report for Non Cafe Studnt in the Date Range',
    'pick data':'Pick Data',
    'generate report for dinner':'Generate Reprot for Dinner',
    'generate report for lunch':'Generate Report for Lunch',
    'generate report for breakfast':'Generate Report for Breakfast',
    'generate report for dinner between the date range':'Generate Repeort for Dinner between the Date Range ',
    'generate report for lunch between the date range':'Generate Repeort for Lunch between the Date Range',
    'generate report for breakfast between the date range':'Generate Repeort for Breakfast between the Date Range',
    'select status':'Select Status here',
    'non cafe':'Non Cafe',
    'serve cafe':'Serve Cafe',
    'payment':'Payment',
    'non cafe student information view and managment':'non cafe student information view and managment',
    'photo':'Photo',

    'samfdtusmicsflbb':'Supe Admin Module for Debre Tabor University Smart ID Card System for Library Book Borrowing',
    'book managment':'Book Managment',
    'staff report':'Staff Report',
    'student reprort':'Student Reprot',
    'student panel':'Student panel',
    'staff panel':'Staff panel',
    'debre tabor university library book borrowing system':'Debre Tabor University Library Book borrowing System',
    'book deleted':'Book file Dleted Successfully',
    'book not deleted':'Book file not Dleted',
    'serial':'Book Id',
    'edition':'Edition',
    'book name':'Book Name',
    'author':'Author',
    'number of book':'Number',
    'report generation for staff':'Report Gneration for Staff User',
    'borrowed book report':'Generate Report for Borrrowed Book',
    'returned book report':'Generate Report for Returned Book',
    'punished user report':'Generate Report for Punished User Book',
    'generate report for borrowed book between the date range':'Generate Report for Borrowed Book Between the Date Range',
    'generate report for returned book between the date range':'Generate Report for Returned Book Between the Date Range',
    'generate report for punished user between the date range':'Generate Report for Punished User Between the Date Rangeራ',
    'report generation for student':'የReport Generation for Student',
    'book registration':'Book REgistration',

    'book user managment':'Book User Managment',
    'return book here':'Return Book Here',
    'returning book status':'Returned Book Status',
    'deadline':'Deadline',
    'current date':'Current Date',
    'borrowed book':'Borrowed Book',
    'borrowed name':'Borrowed Name',
    'number of let day':'Number of let Day',
    'your punishment will be':'The Punishment will be',
    'you left number of days':'You Have Left Number of Days',
    'book returned ontime':'You return Ontime',
    'list of reserved book':'List of Reserved Book',
    'number of reserved':'Number of Reserved',
    'book borrowed student data':'Book Borrowed Student Data',
    'student book file deleted':'Stdent Book File Deleted Successfully',
    'book file not deleted':'Book File Not Deleted',
    'book borrowing panel':'Book Borrowing Panel',
    'view book borrowed user':'View Book Borrowed User',
    'view book returned user':' View Book Returned User',

    'book borrowed staff data':'Book Borrowed Staff Data',
    'staff book file deleted':'Staff Book File Deleted Successfully',
    'staff book file not deleted':'Staff Book File Not Deleted',

    'samfdtuoedcs':'Super Amin Module for Debre Tabor University Outgoing Device Controlling System',
    'view outgoing pc':'View Ourtgoing PC',
    'device managment':'Device Managment',
    'are you sure to leave from the system':'Are you Sure to Leave from the System?',
    'sasrfoedcs':'Student and Staff Registration for Outgoing Electronics Device Control System',
    'personal information for electronics device':'Personal Information for Electronics Device',
    'device serial':'Device Serial',
    'device name':'Device Name',
    'cpu level':'CPU Level',
    'view personal information':'View Personal Information',
    'staff':'Staff',
    'student':'Student',
    'register device':'Register Device Here',
    'register student':'Register Student Here',
    'pc avialable in outgoing device data':'PC Avialable in Ougoing Device Data',
    'outgoing date':'Outgoin Date ',

    'sasdmfoedcs':'Student and Staff Data Manipulation for Outgoing Electronics Device',
    'press this tab tdsd':'Press This tab to Display Staff Data',
    'press this tab tdstd':'Press This tab to Display Student Data',
    'press this tab tdsedd':'Press This tab to Display Staff Electronics Device Data',
    'press this tab tdstedd':'Press This tab to Display Student Electronics Device Data',
    'staff pc avialable':'Staff PC Avialable in the Database',
    'student pc avialable':'Student PC Avialable in the Database',

    'amharic':'የደብረ ታቦር ዩኒቨርሲቲ የተማሪዎች  ምግብ ቤት ሰዓት መቆጣጠሪያ',
    'english':' Debre Tabor University Students Cafeteria Managment System',
    'time boundary setting':'Time Boundary Setting',
    'starting time':'Starting Time',
    'ending time':'Ending Time',
    'select time boundary type':'Select Time Boundary Type',
    'edit time boundary':'Edit Time Boundary',
    'basic clue':'Basic Clue ',
    'about time modification':'About Time Modification',
    'about non cafe':'About Non Cafe Students',
    'about withdrawal and fieldtrip student':'About Withdrawal and Field trip Students',
    'basic clue for manipulation of time boundary':'Here User can view basic clue about time modification',
    'basic clue for manipulation of non cafe student':'Here User can view basic clue about manipulation of non cafe student data',
    'basic clue for manipulation of time withdrawal and fieldtrip student':'Here User can view basic clue about withdrawal and field trip student data',
    'click here to expand and read more':'Click here to expand and read more',
    'n1':'Students have to show their Digital ID infront of Reader machine inline to the machine to be read by the reader and send to the database',
    'n2':'Ticker have to observe weather the students show their ID to the machine or not',
    'n3':'If one ticker miss the correct time boundaary the system show invalid time range notification',
    'n4':'If the student come again to feed the system show red background with student full information and sound notification',
    'n5':'The ticker no need of interaction with the system or machine after starting',
    'n6':'If barcode of a given student Id fade out the machine does not read, so it is the responsibility of ticker to tell for changing Id card ',
    'n7':'The system does not recognize Id of withdrawal, fired or field trip students, so ticker have to take care for this case',
    'student id with barcode':'Stdunet ID with Barcode',
    'student id not insert':'Student id not insert in the breakfast table',
    'student id not insert in lunch table':'Student id not insert in the Lunch table',
    'student id not insert in dinner':'Student id not insert in the Dinner table',

    'cerrunt date':'Current date',
    'please eyoanp':'Please enter your old and new password',

    'dtusmics':'Debre Tabor University Smart ID Card System (SMICS for DTU)',

    'staff profile update':'Staff profile update sucessfully',
    'edit staff profile':'Edite staff profile',
    'active':'Active',
    'deactive':'Deactive',
    'staff profile display':'Staff Profile Display',
    'student profile update':'Student Profile updated successfully',
    'student profile not update try again':'Student Profile not update try agaian',
    'edit student profile':'Edite Student Profile',
    'student profile display':'Student Profile Display',
    'non cafe student update':'Non cafe student data update successfully',
    'edit non cafe student profile':'Edit Non Cafe Students profile',
    'payment date':'Payment Date',
    'non cafe student profile display':'Non cafe student profile display',
    'edit faculty':'Edit faculty data',
    'update success':'Update Success',
    'you have to edit department':'You have to Edite the same data to this page for Department data',
    'update faild try again':'Update faild try again',
    'edit acount':'Edit Staff User Acount',
    'view acount':'View user acount',
    'book file update':'Book file update successfully',
    'edit book file':'Edite book file',
    'view book file':'View book file',
    'book borrowed student file update':'Book brrowed student file update successfully',
    'edit book user student':'Edit book user students',
    'list number':'List number',
    'borrowed':'Borrowed',
    'returned':'Returned',
    'view book borrowed student':'View book borrowed student file',
    'book borrowed staff update':'Book borrowed staff file updated successfully',
    'edit book borrowed staff':'Edit book borrowed staff file',
    'view book borrowed staff':'view book borowed staff file',
    'view owner file':'View electronice device oweners file',
    'you have to edit pc data':'You have to Edite the same data to this page for PC data',
    'edit owner file':'Edit electronics device owners file',

    'create id':'Create Id',
    'generate report':'Report',
    'earned id':'earned Id',
    'not earned id':'Not earned Id',
    'report of earned id':'report of earned id',
    'report of not earned id':'report not of earned id',
    'create losted id':'create losted id',
    'view recreated id':'view recreated id',
    'using faculty':'Id earned. Displayed using Faculty',
    'description':'description',

    'search staff':'Search Staff',
    'student id managment':'Student id management',
    'staff id managment':'Staff id managemnet',
    'search student':'Search Student',
    'not payed':'Not payed',
    'payed':'payed',
    'punishment':'Punishment',
    'select language':'Select Language',
  },
  




  'am':{
    'login':'ግባ',
    'vision':'ራዕይ',
    'mission':'ተልእኮ',
    'value':'እሴት',
    'help':'መረጃ',
    'developer':'ሰሪ',
    'email':'ኢሜል',
    'phone':'ስልክ',
    'name':'ስም',
    'close':'ዝጋ',
    'welcome':'እንኳን ወደ ደብረ ታቦር ዩኒቨርሲቲ ዘመናዊ የመታወቂያ ክርድ ስልት በደህና መጡ፡፡ ለመጀመር ግባ የሚለዉን ይጫኑ',
    'fdescription':'የደብረ ታቦር ዩኒቨርሲቲ በኀብረተሰቡ ፍላጎት-የተዘጋጀ እና በ 2012 ዓ.ም ከፍተኛ የፈጠራ የሰው ኃይል ብቃት እና ጥራት ያለው ትምህርት አቅርቦት  በመስጠት ቁርጠኛ ነው.',
    'smart':'የደብረ ታቦር ዩኒቨርሲቲ',
    'dt':'ዘመናዊ የመታወቂያ ካርድ ስርአት',
    'please': 'እባክዎ የተጠቃሚ ስም እና የይለፍ ቃል ያስገቡ',
    'ema':'ኢሜል (የተጠቃሚ ስም)',
    'about':'ስለ ሰሪዎች',
    'list':'ዋና ዝርዝሮች',
    'val':'እሴቶች',
    'first':' ቅድሚያ ለደንበኛ',
    'teamwork':'የጋራ ስራ',
    'quality':'ጥራት',
    'inovation':'አዲስ ግኝት',
    'scalup':'እድገት እና ዉጤታማነት',
    'ethics':'ታማኝነት እና ስነምግባር',
    'password':'የይለፍ ቃል',
    'level':'ደረጃ',
    'superadmin':'ዋና አስትዳዳሪ',
    'stsa':'የተማሪዎች አገልግሎት አስተዳዳሪ',
    'stss':'የተማሪዎች አገልግሎት ሰራተኛ',
    'ssa':'የሰራተኞች አገልግሎተ አስተዳዳሪ',
    'sss':'የሰራተኞች አገልግሎተ ሰራተኛ',
    'ca':'የምግብ ገልግሎት አስተዳዳሪ',
    'cs':'የምግብ ገልግሎት ስራተኛ',
    'sa':'የጥበቃ አስተዳዳሪ',
    'ss':'የጥበቃ ሰራተኛ',
    'la':'የቤተ-መፀሐፍት አስተዳዳሪ',
    'ls':'የቤተ-መፀሐፍት ስራተኛ',
    'dta':'የመኝታ አገልግሎት አስተዳዳሪ',
    'dts':'የመኝታ አገልግሎት ሰራተኛ',
    'remember':'አስታዉሰኝ',

    'samfdtusmics':'የደብረ ታቦር ዩኒቨረሲቲ ዘመናዊ ካርድ ስልት ዋና አስተዳዳደሪ ክፍለ ድር',
    'date':'ቀን:-',
    'logedas':'አሁን ተጠቃሚ:-',
    'home':'መጀመሪያ ገፅ',
    'cua':'ተጠቃሚ መመዝገቢያ',
    'user managment':'ተጠቃሚ መቆጣጠሪያ',
    'staff managment':'ሰራተኛ መቆጣጠሪያ',
    'student s managment':'ተማሪ መቆጣጠሪያ',
    'cafeteria managment':'ምግብ አገልግሎት መቆጣጠሪያ',
    'library managment':'ቤተ-መፀሐፍት መቆጣጠሪያ',
    'dorm a managment':'መኝታ ቤት መቆጣጠሪያ',
    'security managment':'ደህንነት መቆጣጠሪያ',
    'academics':'የትምህርት ክፍል',
    'academics managment':'የትምህርት ክፍል መቆጣጠሪያ',
    'change password':'የይለፍ ቃል መቀየሪያ',
    'logout':'ዉጣ',
    'dtusicbsps':'የደብረ ታቦር ዩኒቨርሲቲ አንድ ካርድ መሰረት ያደረገ የአገልግሎት መስጫ ስርአት',
    'user register':'ተጠቃሚዉ  በትክክል ተመዝግቧል',
    'user not register':'ተጠቃሚዉ  በትክክል አልተመዘገበም',
    'view user':'ተጠቃሚ ተመልከት',
    'user deleted':'ተጠቃሚዉ  በትክክል ተሰርዟል',
    'user not deleted':'ተጠቃሚዉ  በትክክል አልተሰረዘም',
    'data not avialable':'ጭብጥ የለም እንደገና ሞክር',
    'view activated user':'ያልታገዱ ተጠቃሚዎችን እይ',
    'view deactivated user':'የታገዱ ተጠቃሚዎችን እይ',
    'register staff acount':'ተጠቃሚ መዝግብ',
    'id':'መልያ ቁጥር',
    'staff name':'የተጠቃሚዉ ስም',
    'select user type':'የተጠቃሚዉን ደረጃ ምረጥ',
    'save acount':'አስቀምጥ',
    'cancle':'ሰርዝ',
    'register faculty':'እዚህ ፋኩልቲ መዝግብ',
    'faculty':'ፋኩልቲ:-',
    'status':'ሁኔታ:-',
    'search faculty':'ተ/ክፍል ለማስገባት ፋኩልቲ ምረጥ',
    'select faculty':'ፋኩልቲ ምረጥ',
    'search department':'ልዩ ት/ክፍል ለማስገባት ት/ክፍል ምረጥ',
    'department':'ት/ክፍል',
    'select department':'ት/ክፍል ምረጥ',
    'faculty entered':'ፋኩልቲ በትክክል ተመዝግቧል',
    'return':'ተመለስ',
    'return to home page':'ወደ መጀመሪያዉ ገፅ ተመለስ',
    'please sfte department':'ተ/ክፍል ለማስገባት ፋኩልቲ ምረጥ',
    'reset':'ዳግም አስጀምር',
    'department entered':'ት/ክፍል በትክክል ተመዝግቧል',
    'department not entered':'ት/ከፍል በትክክል አልተመዘገበም',
    'please sdte stream':'ልዩ ት/ክፍል ለማስገባት ት/ክፍል ምረጥ',
    'stream':'ልዩ ት/ክፍል',
    'stream entered':'ልዩ ት/ክፍል በትክክል ተመዝግቧል',
    'stream not entered':'ልዩ ት/ከፍል በትክክል አልተመዘገበም',
    'press this tab tdfd':'የፋኩለቲ ጭብጥ ለማየት ይህን አዝራር ተጫን',
    'please eyunap':'እባክዎ የተጠቃሚ ስም እና የይለፍ ቃል ያስገቡ',
    'old password':'የበፊት የይለፍ ቃል:- ',
    'new password':'አዲስ የይለፍ ቃል:-',
    'confirm password':'የይለፍ ቃሉን አረጋግጥ:-',
    'change':'ቀይር',
    'view user':'ተጠቃሚዎችን እይ',
    'user id':'መለያ ቁጥር',
    'full name':'ሙሉ ስም',
    'user status':'የተጠቃሚዉ ሁኔታ',
    'action':'ተግባር',
    'user name':'መጠቀሚያ ስም',
    'user type':'የተጠቃሚ ደረጃ ',

    'samfdtusmicsfstaff':'የደብረ ታቦር ዩኒቨረሲቲ ዘመናዊ ካርድ ስልት ዋና አስተዳዳደሪ ክፍለ ድር ለሰራተኛ',
    'staff registration':'ሰራተኛ መመዝገቢያ',
    'staff barcode generation':'የሰራተኛ መለያ ደንብ መስሪያ',
    'register staff':'እዚህ ሰራተኛ መዝግብ',
    'sex':'ፆታ',
    'year':'ዓመት', 
    'ac_year':'ዓ.ም',
    'upload photo':'ፎቶ ጫን',
    'remove':'አስወግድ',
    'select image':'ፎቶ ምረጥ',
    'female':'ሴት',
    'male':'ወንድ',
    'generate barcode':'የሰራተኛ መለያ ደንብ ስራ',
    'select stream':'ልዩ ት/ክፍል ምረጥ',
    'change image':'ፎቶ ቀይር',
    'list of employee data':'የሰራተኛ ጭብጥ ዝርዝር',
    'staff profile deleted':'የሰራተኛዉ መረጃ በትክክል ተሰርዟል',
    'staff profile not deleted':'የሰራተኛዉ መረጃ አልተሰረዘም',
    'staff avialable':'ሰራተኛ በሰንጠረዡ ዉስጥ አለ',
    'ac_year':'ዓ.ም',
    'status':'ሁኔታ',

    'samfdtusmicsfstudent':'የደብረ ታቦር ዩኒቨረሲቲ ዘመናዊ ካርድ ስልት ዋና አስተዳዳደሪ ክፍለ ድር ለተማሪ',
    'student registration':'ተማሪ መመዝገቢያ',
    'student barcode registration':'የተማሪ መለያ ደንብ መስሪያ',
    'year':'ዓመት',
    'student avialable':'ተማሪ በሰንጠረዡ ዉስጥ አለ',

    'samfdtucms':'የደብረ ታቦር ዩኒቨረሲቲ ዘመናዊ ካርድ ስልት ዋና አስተዳዳደሪ ክፍለ ድር ለምግብ አገልግሎት',
    'register non cafe':'ምግብ አገልግሎት የማይጠቀሙትን መመዝገቢያ',
    'manage data':'ጭብጥ ተቆጣጠር',
    'generate cafe user report':'ምግብ አገልግሎት የሚጠቀሙትን መረጃ ስራ',
    'generate non cafe report':'ምግብ አገልግሎት የማይጠቀሙትን መረጃ ስራ',
    'generate rerort for non cafe student in the date range':'በቀነ ገድቡ መሰረት ምግብ አገልግሎት የማይጠቀሙትን መረጃ ስራ',
    'pick data':'መረጃዉን ለይተህ አዉጣ',
    'generate report for dinner':'የእራት ሰዓት መረጃ ስራ',
    'generate report for lunch':'የምሳ ሰዓት መረጃ ስራ',
    'generate report for breakfast':'የቁርስ ሰዓት መረጃ ስራ',
    'generate report for dinner between the date range':'በቀነ ገድቡ መሰረት የራት ሰዓት መረጃ ስራ',
    'generate report for lunch between the date range':'በቀነ ገድቡ መሰረት የምሳ ሰዓት መረጃ ስራ',
    'generate report for breakfast between the date range':'በቀነ ገድቡ መሰረት የቁርስ ሰዓት መረጃ ስራ',
    'select status':'ሁኔታ ምረጥ',
    'non cafe':'ምግብ አገልግሎት የማይጠቀም',
    'serve cafe':'ምግብ አገልግሎት የሚጠቀም',
    'payment':'ክፍያ',
    'non cafe student information view and managment':'ምግብ አገልግሎት የማይጠቀሙ ተማሪዎችን መረጃ ማሳያ እና መቆጣጠሪያ',
    'photo':'ፎቶ',

    'samfdtusmicsflbb':'የደብረ ታቦር ዩኒቨረሲቲ ዘመናዊ ካርድ ስልት ዋና አስተዳዳደሪ ክፍለ ድር ለቤተ-መፀሐፍት',
    'book managment':'መፀሐፍ መቆጣጠሪያ',
    'staff report':'የሰራተኛ መረጃ',
    'student reprort':'የተማሪ መረጃ',
    'student panel':'የተማሪ ክፍለ ድር',
    'staff panel':'የሰራተኛ ክፍለ ድር',
    'debre tabor university library book borrowing system':'የደብረ ታቦር ዩኒቨርሲቲ የመፀሃፍ ማዋሻ ስርአት',
    'book deleted':'መፀሐፉ ተሰርዟል',
    'book not deleted':'መፀሐፉ አልተሰረዘም',
    'serial':'የመፀሐፉ መለያ ቁጥር',
    'edition':'እትም',
    'book name':'የመፀሐፉ ስም',
    'author':'የፀሐፊዉ ስም',
    'number of book':'የመፀሐፍ ብዛት',
    'report generation for staff':'የሰራተኛ መረጃ መስሪያ',
    'borrowed book report':'የተዋሱ መፀሐፍትን መረጃ ስራ',
    'returned book report':'የተመለሱሱ መፀሐፍትን መረጃ ስራ',
    'punished user report':'የተቀጡ ተጠቃሚዎችን መረጃ ስራ',
    'generate report for borrowed book between the date range':'በቀነ ገድቡ መሰረት የተዋሱ መፀሐፍትን መረጃ ስራ',
    'generate report for returned book between the date range':'በቀነ ገድቡ መሰረት የተመለሱሱ መፀሐፍትን መረጃ ስራ',
    'generate report for punished user between the date range':'በቀነ ገድቡ መሰረት የተቀጡ ተጠቃሚዎችን መረጃ ስራ',
    'report generation for student':'የተማሪ መረጃ መስሪያ',
    'book registration':'የመፀሐፍ መመዝገቢያ',

    'book user managment':'መፀሐፍ ተጠቃሚ መቆጣጠሪያ',
    'return book here':'እዚህ መፀሐፍ መልስ',
    'returning book status':'የተመለሰዉ መፀሐፍ ሁኔታ',
    'deadline':'የመመለሻ ቀን',
    'current date':'ዛሬ ቀን',
    'borrowed book':'የተዋሰዉ መፀሐፍ ስም',
    'borrowed name':'የተዋሰዉ ሰዉ ስም',
    'number of let day':'የእላፊ ቀን ብዛት',
    'your punishment will be':'ስለዚህ መቀጫዉ',
    'you left number of days':'የተወሰነ ቀን ይቀርሀል',
    'book returned ontime':'በዕለተ ቀኑ መልሰሀል',
    'list of reserved book':'የተዋሱ መፀሐፎች ዝርዝር',
    'number of reserved':'የተዋሱ መፀሐፎች ብዛት',
    'book borrowed student data':'መፀሐፍ የተዋሱ ተማሪዎች ጭብጥ',
    'student book file deleted':'መፀሐፍ የተዋሰዉ ተማሪ ተሰርዟል',
    'student book file not deleted':'መፀሐፍ የተዋሰዉ ተማሪ አልተሰረዘም',
    'book borrowing panel':'መፀሐፍ ማዋሻ ቦታ',
    'view book borrowed user':'መፀሐፍ የተዋሱ ተጠቃሚዎችን እይ',
    'view book returned user':'መፀሐፍ የመለሱ ተጠቃሚዎችን እይ',

    'book borrowed staff data':'መፀሐፍ የተዋሱ ሰራተኞች ጭብጥ',
    'staff book file deleted':'መፀሐፍ የተዋሰዉ ሰራተኛ ተሰርዟል',
    'staff book file not deleted':'መፀሐፍ የተዋሰዉ ሰራተኛ አልተሰረዘም',

    'samfdtuoedcs':'የደብረ ታቦር ዩኒቨርሲቲ ወደ ዉጭ የሚወጡ ላፕቶፖች መቆጣጠሪያ ዋና አስተዳዳሪ ክፍለ ድር',
    'view outgoing pc':'የሚወጡ ላፕቶፖችን መረጃ እይ',
    'device managment':'የላፕቶፕ መቆጣጠሪያ',
    'are you sure to leave from the system':'ከመስሪያ ክልሉ ለመዉጣት እርግጠኛ ነህ?',
    'sasrfoedcs':'ተማሪ እና ሰራተኛ መመዝገቢያ ወደ ዉጭ ለሚወጡ ላፕቶፖች',
    'personal information for electronics device':'የላፕቶፕ ባለንብረቶች መረጃ',
    'device serial':'የእቃዉ  መለያ ቁጥር',
    'device name':'የእቃዉ  ስም',
    'cpu level':'የፍጥነት ደረጃ',
    'view personal information':'የባለቤቱን ጭብጥ እይ',
    'staff':'ሰራተኛ',
    'student':'ተማሪ',
    'register device':'ላፕቶፕ እዚህ መዝግብ',
    'register student':'ተማሪ እዚህ መዝግብ',
    'pc avialable in outgoing device data':'የወጣ ላፕቶፕ በሰንጠረዡ ዉስጥ አለ',
    'outgoing date':'የወጣበት ቀን ',

    'sasdmfoedcs':'የተማሪ እና የሰራተኛ መቆጣጠሪያ ወደ ዉጭ ለሚወጡ ላፕቶፖች',
    'press this tab tdsd':'የሰራተኞችን ጭብጥ ለማየት ይሄን አዝራር ተጫን',
    'press this tab tdstd':'የተማሪዎችን ጭብጥ ለማየት ይሄን አዝራር ተጫን',
    'press this tab tdsedd':'የሰራተኞችን ላፕቶፕ ጭብጥ ለማየት ይሄን አዝራር ተጫን',
    'press this tab tdstedd':'የተማሪዎችን ላፕቶፕ ጭብጥ ለማየት ይሄን አዝራር ተጫን',
    'staff pc avialable':'የሰራተኞ ላፕቶፕ በሰንጠረዡ ዉስጥ አለ',
    'student pc avialable':'የተማሪዎች ላፕቶፕ በሰንጠረዡ ዉስጥ አለ',

    'amharic':'Debre Tabor University Students Cafeteria Managment System',
    'english':'የደብረ ታቦር ዩኒቨርሲቲ የተማሪዎች  ምግብ ቤት ሰዓት መቆጣጠሪያ',
    'time boundary setting':'የሰዓት ገደብ ማስተካከያ',
    'starting time':'መጀመሪያ ሰዓት',
    'ending time':'መጨረሻ ሰዓት',
    'select time boundary type':'የሰዓት ገደብ እይነት ምረጥ',
    "edit time boundary":'የሰዓት ገደብ አስተካክል',
    'basic clue':'መሰረታዊ መረጃ ',
    'about time modification':'ስለ ሰዓት ቅየራ',
    'about non cafe':'የምግብ አገልግሎት ስለማይጠቀሙ ተማሪዎች',
    'about withdrawal and fieldtrip student':'ስላቋረጡ እና ለተግባር ስራ ስለወጡ  ተማሪዎች',
    'basic clue for manipulation of time boundary':'እዚህ ላይ ተጠቃሚዉ ስለ ሰዓት አቀያየር ዋና መረጃ ማግኘት ይችላል',
    'basic clue for manipulation of non cafe student':'እዚህ ላይ ተጠቃሚዉ የምግብ አገልግሎት ስለማይጠቀሙ ተማሪዎች ዋና መረጃ ማግኘት ይችላል',
    'basic clue for manipulation of time withdrawal and fieldtrip student':'እዚህ ላይ ተጠቃሚዉ የምግብ ስለቋረጡ እና ለተግባር ስራ ስለወጡ  ተማሪዎች ዋና መረጃ ማግኘት ይችላል',
    'click here to expand and read more':'እስፍቶ ለማንበብ ይህን አዝራር ተጫን',
    'n1':'የተማሪዎች መለያ ቁጥር በመሳሪያዉ ተነቦ ወደ ተጠቃሚዎች ማህደር ይገባ ዘንድ ተማሪዎች መታወቂያቸዉን በሚያነበዉ መሳሪያ ትክክል ፊትለፊት ማሳየት አለባቸዉ',
    'n2':'ተማሪዎች መታወቂያቸዉን ለሚያነበዉ መሳሪያ ማሳየት አለማሳየታቸዉን ለማወቅ ተቆጣጣሪዎች መመልከት አለባቸዉ',
    'n3':'ማንኛዉም ተቆጣጣሪ ትክክለኛዉን የመመገቢያ ሰዓት ቢሰሳት ስርአቱ ሰዓቱ ትክክል አይደለም የሚል ፅሑፍ ያሳያል',
    'n4':'ማንኛዉም ተማሪ ሁለተኛ ለመመገብ ቢመጣ ስርኣቱ የተማሪዉን ሙሉ መረጃ በፅሑፍ እና በድምፅ ያሳያል ይናገራልም',
    'n5':'ተቆጣጣሪዎች አንድ ግዜ  ካስጀመሩ በኋላ ከስርኣቱ ጋራ ምንም አይንት ግንኙነት ማድረግ አይጠበቅባቸዉም',
    'n6':'ተቆጣጣሪዎች የተማሪዎች መታወቂያ ካርድ ከተሰበረ ወይንም ምስጢር ቁጥሩ ከተፋቀ እንዲቀይሩ ማስጠንቀቅ አለባቸዉ',
    'n7':'ስርአቱ የተባረረ፣ የቋረጠ ወይንም ለተግባር ስራ የወጣን ተማሪ አያስተናግድም',
    'student id with barcode':'የተማሪ ምስጢራዊ መለያ ቁጥር',
    'student id not insert':'የተማሪዉ መለያ ቁጥር ቁርስ ሰኣት ዉስጥ አልገባም',
    'student id not insert in lunch table':'የተማሪዉ መለያ ቁጥር ምሳ ሰኣት ዉስጥ አልገባም',
    'student id not insert in dinner':'የተማሪዉ መለያ ቁጥር እራት ሰኣት ዉስጥ አልገባም',

    'cerrunt date':'ዛሬ ቀን',
    'please eyoanp':'እባክዎ የነበረዉን እና አዲስ የይለፍ ቃል ያስገቡ',

    'dtusmics':'የደብረ ታቦር ዩኒቨርሲቲ ዘመናዊ ካርድ ስርአት',

    'staff profile update':'የሰራተኛዉ መረጃ ተቀይሯል',
    'edit staff profile':'የሰራተኞችን መረጃ ማስተካከያ',
    'active':'ያልታገደ',
    'deactive':'የታገደ',
    'staff profile display':'የሰራተኞች ሙሉ መረጃ ',
    'student profile update':'የተማሪዉ መረጃ ተቀይሯል',
    'student profile not update try again':'የተማሪዉ መረጃ አልተቀየረም እንደገና ሞክር',
    'edit student profile':'የተማሪዎችን መረጃ ማስተካከያ',
    'student profile display':'የተማሪዎች ሙሉ መረጃ',
    'non cafe student update':'ምግብ አገልግሎት የማይጠቀሙ ተማሪዎች መረጃ ተስተካክሏል',
    'edit non cafe student profile':'ምግብ አገልግሎት የማይጠቀሙ ተማሪዎችን መረጃ ማስተካከያ',
    'payment date':'የተከፈለበት ቀን',
    'non cafe student profile display':'ምግብ አገልግሎት የማይጠቀሙ ተማሪዎችን ሙሉ መረጃ',
    'edit faculty':'የፋኩልቲ መረጃ ማስተካከያ',
    'update success':'መረጃዉ ተስተካክሏል',
    'you have to edit department':'እዚህ ገፅ ላይ በተመሳሳይ የትምህርት ክፍል መረጃ ቀይር',
    'update faild try again':'ቅየራዉ አልተሳካም እንደገና ሞክር',
    'edit acount':'የመጠቀሚያ መረጃን ማስተካከያ',
    'view acount':'የመጠቀሚያ መረጃዎችን መመልከቻ',
    'book file update':'የመፅሐፍት መረጃ ተስተካክሏል',
    'edit book file':'የመፅሐፍት መረጃ ማስተካከያ',
    'view book file':'የመፅሐፍት መረጃ መመልከቻ',
    'book borrowed student file update':'መፅሐፍ የተዋሰዉ ተማሪ መረጃ ተስተካክሏል',
    'edit book user student':'የመጽሐፍ የተዋሱ ተማሪዎችን መረጃ ማስተካከያ',
    'list number':'ተራ ቁጥር',
    'borrowed':'ያልመለሰ',
    'returned':'የመለሰ',
    'view book borrowed student':'መጽሐፍ የተዋሱ ተማሪዎችን መረጃ መመልከቻ',
    'book borrowed staff update':'መፅሐፍ የተዋሰዉ ሰረተኛ መረጃ ተስተካክሏል',
    'edit book borrowed staff':'መጽሐፍ የተዋሱ ሰራተኞችን መረጃ ማስተካከያ',
    'view book borrowed staff':'የመጽሐፍ የተዋሱ ሰራተኞችን መረጃ መመልከቻ',
    'view owner file':'የላፕቶፕ ባለ ንብረቶችን መረጃ መመልከቻ',
    'you have to edit pc data':'እዚህ ገፅ ላይ በተመሳሳይ የትምህርት ክፍየላፕቶፕ መረጃን ቀይር',
    'edit owner file':'የላፕቶፕ ባለ ንብረቶችን መረጃ ማስተካከያ',

    'create id':'መታወቂያ ስራ',
    'generate report':'ማስረጃ',
    'earned id':'መታወቂያ የወሰዱ',
    'not earned id':'መታወቂያ ያልወሰዱ',
    'report of earned id':'መታወቂያ የወሰዱ ማስረጃ',
    'report of not earned id':'መታወቂያ ያልወሰዱ ማስረጃ',
    'create losted id':'የጠፉ መታወቂያዎችን ስራ',
    'view recreated id':'በድጋሜ የተሰሩ መታወቂያዎችን እይ',
    'using faculty':'መታወቂያ የወሰዱ ማስረጃ በፋኩልቲ',
    'description':'ገለፃ',

    'search staff':'ሰራተኛዉን ፈልግ',
    'student id managment':'የተማሪዎች መታወቂያ መስሪያ',
    'staff id managment':'የተሰራተኞች መታወቂያ መስሪያ',
    'search student':'ተማሪዉን ፈልግ',
    'not payed':'አልተከፈለም',
    'payed':'ተከፍሏል',
    'punishment':'ቅጣት',
    'select language':'ቋንቋ ምረጥ',
  }
};
$(function(){
  $('.translate').click(function(){
    var lang=$(this).attr('id');
    $('.lang').each(function(index, element){
      $(this).text(arrlang[lang][$(this).attr('key')]);
    });
  });
});
